// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc3824.CompetitionRobot.subsystems;

import org.usfirst.frc3824.CompetitionRobot.RobotMap;
import org.usfirst.frc3824.CompetitionRobot.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class Pickup extends Subsystem
{
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController wheelPickupTalon = RobotMap.pickupWheelPickupTalon;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand()
    {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }

    //====================================================================================
    // Pickup Control methods
    //====================================================================================
    /**
     * <b><u>Pickup Control Method</u></b>
     * <p>
     * Pickup In</p>
     */
    public void setPickupIn()
    {
        wheelPickupTalon.set(0.75);
    }

    /**
     * <b><u>Pickup Control Method</u></b>
     * <p>
     * Pickup Out</p>
     */
    public void setPickupOut()
    {
        wheelPickupTalon.set(-0.75);
    }

    /**
     * <b><u>Pickup Control Method</u></b>
     * <p>
     * Pickup Off</p>
     */
    public void setPickupOff()
    {
        wheelPickupTalon.set(0.0);
    }
}
