// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc3824.CompetitionRobot.subsystems;
import org.usfirst.frc3824.CompetitionRobot.RobotMap;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class Vacuum extends Subsystem
{
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController vacuum = RobotMap.vacuumVacuum;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private boolean m_vacuumActive = false;
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand()
    {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        vacuum.set(0);
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    /**
     * <b><u>Vacuum Control Method</u></b>
     * <p>
     * Vacuum On</p>
     */
    public void setVacuumOn()
    {
        vacuum.set(1.0);
        m_vacuumActive = true;
    }
    /**
     * <b><u>Vacuum Control Method</u></b>
     * <p>
     * Vacuum Off</p>
     */
    public void setVacuumOff()
    {
        vacuum.set(0.0);
        m_vacuumActive = false;
    }
    /**
     * <b><u>Vacuum Control Method</u></b>
     * <p>
     * Vacuum Toggle</p>
     */
    public void toggleVacuum()
    {
        if (m_vacuumActive == true)
        {
            // if vacuum is on, turn it off!
            vacuum.set(0.0);
            m_vacuumActive = false;
        } else if (m_vacuumActive == false)
        {
            // if vacuum is off, turn it on!
            vacuum.set(1.0);
            m_vacuumActive = true;
        }
    }
}
