// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc3824.CompetitionRobot.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;
import org.usfirst.frc3824.CompetitionRobot.Constants;

/**
 *
 */
public class AutonomousTwoBallPostCommon extends CommandGroup
{

    public AutonomousTwoBallPostCommon()
    {
        addSequential(new ChassisDriveStraight(Constants.AUTONOMOUS_TWO_BALL_FORWARD_SHOOT_DRIVE_TIME,
                                               Constants.AUTONOMOUS_TWO_BALL_FORWARD_SHOOT_DRIVE_POWER,
                                               Constants.AUTONOMOUS_TWO_BALL_FORWARD_SHOOT_DRIVE_ANGLE, true));
        
        // shoot the second ball
        addSequential(new CannonShoot());

        // get ready to pickup a ball if need be in teleoperated
        addParallel(new SetShooterAngle(Constants.SHOOTER_PICKUP_POSITION));
        addSequential(new VacuumOff());
    }
}
