// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3824.CompetitionRobot.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;
import org.usfirst.frc3824.CompetitionRobot.Constants;

/**
 *
 */
public class BallTransferfromAuxtoMain extends CommandGroup {
    
    public  BallTransferfromAuxtoMain() 
    {
        // Transfers the Ball from the Auxiliary arm to the main shooter.
        
        addSequential(new SetShooterAngle(Constants.SHOOTER_ANGLE_MAX_VALUE));
        //addSequential(new SetAuxiliaryLeftAngle(Constants.AUX_TRANSFER_ANGLE));
        addSequential(new AuxiliaryLeftRetractandVacuumOff());
        addParallel(new VacuumOn());
    }
}
