// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc3824.CompetitionRobot.commands;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3824.CompetitionRobot.Constants;
import org.usfirst.frc3824.CompetitionRobot.Robot;
/**
 *
 */
public class CannonShootThreePistons extends Command
{
    private static Timer timer = new Timer();
    public CannonShootThreePistons()
    {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.shooter);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    // Called just before this Command runs the first time
    protected void initialize()
    {
        // Fires the Shooter solenoids and starts the timer
        Robot.shooter.setShooterSolenoidsThreePistons(true);
        timer.reset();
        timer.start();
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute()
    {
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished()
    {
        return timer.get() >= Constants.CANNON_SHOOT_TIME;
    }
    // Called once after isFinished returns true
    protected void end()
    {
        // retracts the shooter solenoids
        // Note: retract all silenoids just in case
        Robot.shooter.setShooterSolenoids(false);
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted()
    {
        this.end();
    }
}
