// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc3824.CompetitionRobot.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;
import org.usfirst.frc3824.CompetitionRobot.Constants;

/**
 *
 */
public class GoHome extends CommandGroup
{
    public GoHome()
    {
        // Setup the robot for start of match     
        addSequential(new SetShooterAngle(Constants.SHOOTER_HOME_POSITION));
        //addSequential(new SetAuxiliaryLeftAngle(Constants.AUX_HOME_POSITION));
        //addSequential(new AuxiliaryLeftVerticalRetract());

        // Disable the vacuum
        addSequential(new VacuumOff());
        //addParallel(new AuxiliaryLeftVacuumOff());

        // Stop the ball pickup wheels
        addParallel(new PickupBallStop());
    }
}
