// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc3824.CompetitionRobot.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3824.CompetitionRobot.Robot;
/**
 *
 */
public class  SetAuxiliaryLeftAngle extends Command {
    private double angle, startVoltage, targetVoltage;
    private int motorDirection;
    public SetAuxiliaryLeftAngle(double angleParam) {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.auxiliaryLeft);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        angle = angleParam;
    }
    public SetAuxiliaryLeftAngle() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.auxiliaryLeft);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    // Called just before this Command runs the first time
    protected void initialize() {
        startVoltage = Robot.auxiliaryLeft.getShooterAngle().getAverageVoltage();
        targetVoltage = angle / 54;
        if(targetVoltage > startVoltage)
            motorDirection = 1;
        else
            motorDirection = -1;
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        Robot.auxiliaryLeft.getAuxilaryMotor().set(motorDirection);
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return Math.abs(Robot.auxiliaryLeft.getShooterAngle().getAverageVoltage() - targetVoltage) < 0.05;
    }
    // Called once after isFinished returns true
    protected void end() {
       Robot.auxiliaryLeft.getAuxilaryMotor().set(0); 
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
        end();
    }
}
